// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<main class=\"container text-center flex-grow-1 d-flex flex-column justify-content-center\"><h1 class=\"hero-title mb-3\">Welcome to Loom</h1><p class=\"hero-subtitle mb-5\">A simple and modern Go Web Framework.</p><div class=\"row justify-content-center\"><div class=\"col-md-6\"><div class=\"card shadow-sm p-5\"><div class=\"card-body\"><h5 class=\"card-title\">Get Started</h5><p class=\"card-text my-4\">Edit <code>PageController</code> to customize this page. Use the CLI tool to generate controllers, views, and routes.</p><a href=\"https://getbootstrap.com/docs/5.3/getting-started/introduction/\" class=\"btn btn-lg px-4 btn-primary m-1\" target=\"_blank\">Bootstrap Docs</a> <a href=\"https://go.dev/doc/\" class=\"btn btn-lg px-4 btn-outline-secondary m-1\" target=\"_blank\">Go Docs</a></div></div></div></div></main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
